---
static_column_names:
  {
    "web_name": "Player Name",
    "position": "Position",
    "team_name": "Team",
    "total_points": "Total Points",
    "form": "Form",
    "now_cost": "Current Price",
    "selected_by_percent": "Selected by %",
    "event_points": "Round Points",
    "goals_scored": "Goals",
    "assists": "Assists",
    "goal_involvement": "Goal Involvement (GI)",
    "goals_per_90": "Goals/90 min",
    "assists_per_90": "Assists/90 min",
    "goal_involvement_per_90": "GI/90 min",
    "clean_sheets": "Clean Sheets",
    "penalties_missed": "Penalties Missed",
    "goals_conceded": "Goals Conceded",
    "goals_conceded_per_90": "Goals Conceded/90 min",
    "own_goals": "Own Goals",
    "penalties_saved": "Penalties Saved",
    "saves": "Saves",
    "value_form": "Points/Form",
    "value_season": "Points/Million",
    "points_per_game": "Points/Game",
    "bonus": "Bonus Points",
    "bps": "BPS",
    "expected_assists": "xA",
    "expected_assists_per_90": "xA/90 min",
    "expected_goals": "xG",
    "expected_goals_per_90": "xG/90 min",
    "expected_goal_involvements": "xGI",
    "expected_goal_involvements_per_90": "xGI/90 min",
    "expected_goals_conceded": "xGC",
    "expected_goals_conceded_per_90": "xGC/90 min",
    "influence": "Influence",
    "creativity": "Creativity",
    "threat": "Threat",
    "ict_index": "ICT Index",
    "yellow_cards": "Yellow Cards",
    "red_cards": "Red Cards",
    "minutes": "Minutes Played",
    "opponent_1": "Next Fixture 1",
    "opponent_2": "Next Fixture 2",
    "opponent_3": "Next Fixture 3",
    "opponent_4": "Next Fixture 4",
    "opponent_5": "Next Fixture 5",
  }

gw_column_names:
  {
    "total_points": "Round Points",
    "transfers_balance": "Net transfers",
    "transfers_in": "Transfers In",
    "transfers_out": "Transfers Out",
    "value": "Price",
    "cumulative_points": "Cumulative Points",
    "average_bonus": "Moving Average: Bonus Points",
    "average_bps": "Moving Average: BPS",
    "average_xa": "Moving Average: xA",
    "average_xg": "Moving Average: xG",
    "average_xgi": "Moving Average: xGI",
    "average_xgc": "Moving Average: xGC",
    "cumulative_assists": "Cumulative Assists",
    "cumulative_clean_sheets": "Cumulative Clean Sheets",
    "cumulative_goals_scored": "Cumulative Goals Scored",
    "cumulative_goals_conceded": "Cumulative Goals Conceded",
    "cumulative_saves": "Cumulative Saves",
    "average_influence": "Moving Average: Influence",
    "average_creativity": "Moving Average: Creativity",
    "average_threat": "Moving Average: Threat",
    "average_ict_index": "Moving Average: ICT Index",
    "form": "Moving Average: Form",
    "cumulative_goal_involvement": "Cumualtive Goal Involvement",
    "cumulative_minutes": "Cumulative Minutes Played",
    "cumulative_goals_per_90": "Cumulative Goals Scored/90 min",
    "cumulative_assists_per_90": "Cumulative Assists/90 min",
    "cumulative_goal_involvement_per_90": "Cumulative Goal Involvement/90 min",
    "cumulative_xa": "Cumulative xA",
    "cumulative_xg": "Cumulative xG",
    "cumulative_xgi": "Cumulative xGI",
    "cumulative_xgc": "Cumulative xGC",
  }

all_players_hidden_columns:
  [
    "chance_of_playing_this_round",
    "fixture_difficulty_1",
    "fixture_difficulty_2",
    "fixture_difficulty_3",
    "fixture_difficulty_4",
    "fixture_difficulty_5",
  ]

mid_hidden_columns:
  [
    "goals_conceded",
    "goals_conceded_per_90",
    "own_goals",
    "saves",
    "penalties_saved",
  ]

def_hidden_columns: ["saves", "penalties_saved"]

fwd_hidden_columns:
  [
    "clean_sheets",
    "goals_conceded",
    "goals_conceded_per_90",
    "own_goals",
    "saves",
    "penalties_saved",
  ]

gkp_hidden_columns:
  [
    "goals_scored",
    "assists",
    "goal_involvement",
    "goals_per_90",
    "assists_per_90",
    "goal_involvement_per_90",
    "penalties_missed",
    "expected_goals",
    "expected_assists",
    "expected_goal_involvements",
  ]
position_options: ["All", "GKP", "DEF", "MID", "FWD"]
