---
midfielder_stats_table_columns:
  {
    "web_name": "Player Name",
    "position": "Position",
    "team_name": "Team",
    "total_points": "Total Points",
    "now_cost": "Current Price",
    "selected_by_percent": "Selected by %",
    "event_points": "Round Points",
    "goals_scored": "Goals",
    "assists": "Assists",
    "goal_contribution": "Goals+Assists",
    "minutes": "Minutes Played",
    "goals_per_90": "Goals per 90 min",
    "assists_per_90": "Assists per 90 min",
    "goal_contribution_per_90": "G+A per 90 min",
    "form": "Form",
    "clean_sheets": "Clean Sheets",
    "penalties_missed": "Penalties Missed",
    "yellow_cards": "Yellow Cards",
    "red_cards": "Red Cards",
    "bonus": "Bonus Points",
    "bps": "BPS",
    "influence": "Influence",
    "creativity": "Creativity",
    "threat": "Threat",
    "ict_index": "ICT Index",
    "value_form": "Points/Form",
    "value_season": "Points per Million",
    "points_per_game": "Points per Game",
    "chance_of_playing_this_round": "Chance of Playing",
  }

defender_stats_table_columns:
  {
    "web_name": "Player Name",
    "position": "Position",
    "team_name": "Team",
    "total_points": "Total Points",
    "now_cost": "Current Price",
    "selected_by_percent": "Selected by %",
    "event_points": "Round Points",
    "goals_scored": "Goals",
    "assists": "Assists",
    "goal_contribution": "Goals+Assists",
    "minutes": "Minutes Played",
    "goals_per_90": "Goals per 90 min",
    "assists_per_90": "Assists per 90 min",
    "goal_contribution_per_90": "G+A per 90 min",
    "form": "Form",
    "clean_sheets": "Clean Sheets",
    "goals_conceded": "Goals Conceded",
    "goals_conceded_per_90": "Goals Conceded per 90 min",
    "own_goals": "Own Goals",
    "penalties_missed": "Penalties Missed",
    "yellow_cards": "Yellow Cards",
    "red_cards": "Red Cards",
    "saves": "Saves",
    "bonus": "Bonus Points",
    "bps": "BPS",
    "influence": "Influence",
    "creativity": "Creativity",
    "threat": "Threat",
    "ict_index": "ICT Index",
    "value_form": "Points/Form",
    "value_season": "Points per Million",
    "points_per_game": "Points per Game",
    "chance_of_playing_this_round": "Chance of Playing",
  }

attacker_stats_table_columns:
  {
    "web_name": "Player Name",
    "position": "Position",
    "team_name": "Team",
    "total_points": "Total Points",
    "now_cost": "Current Price",
    "selected_by_percent": "Selected by %",
    "event_points": "Round Points",
    "goals_scored": "Goals",
    "assists": "Assists",
    "goal_contribution": "Goals+Assists",
    "minutes": "Minutes Played",
    "goals_per_90": "Goals per 90 min",
    "assists_per_90": "Assists per 90 min",
    "goal_contribution_per_90": "G+A per 90 min",
    "form": "Form",
    "penalties_missed": "Penalties Missed",
    "yellow_cards": "Yellow Cards",
    "red_cards": "Red Cards",
    "bonus": "Bonus Points",
    "bps": "BPS",
    "influence": "Influence",
    "creativity": "Creativity",
    "threat": "Threat",
    "ict_index": "ICT Index",
    "value_form": "Points/Form",
    "value_season": "Points per Million",
    "points_per_game": "Points per Game",
    "chance_of_playing_this_round": "Chance of Playing",
  }

gk_stats_table_columns:
  {
    "web_name": "Player Name",
    "position": "Position",
    "team_name": "Team",
    "total_points": "Total Points",
    "now_cost": "Current Price",
    "selected_by_percent": "Selected by %",
    "event_points": "Round Points",
    "minutes": "Minutes Played",
    "form": "Form",
    "clean_sheets": "Clean Sheets",
    "goals_conceded": "Goals Conceded",
    "goals_conceded_per_90": "Goals Conceded per 90 min",
    "own_goals": "Own Goals",
    "penalties_saved": "Penalties Saved",
    "yellow_cards": "Yellow Cards",
    "red_cards": "Red Cards",
    "saves": "Saves",
    "bonus": "Bonus Points",
    "bps": "BPS",
    "influence": "Influence",
    "creativity": "Creativity",
    "threat": "Threat",
    "ict_index": "ICT Index",
    "value_form": "Points/Form",
    "value_season": "Points per Million",
    "points_per_game": "Points per Game",
    "chance_of_playing_this_round": "Chance of Playing",
  }
