# This is a basic workflow that is manually triggered

name: Trigger Database update from FPL API

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
  # Add matchday updates - Every 1 hour on days that a game is being played during the match slots.
    - cron: '30 13-18/1 9,15,16,22,23,29,30 4 *'
    - cron: '30 19-22/1 17,21,25-27, 4 *'
    - cron: '30 19-22/1 1,3,4,15,20,28 5 *'
    - cron: '30 13-18/1 6-8,13,14 5 *'
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}
    - name: Conda env setup
      uses : conda-incubator/setup-miniconda@v2
      with:
        activate-environment: fpl-db-py39
        miniconda-version: "latest"
        environment-file: environment.yml
        auto-activate-base: false
        use-only-tar-bz2: true
    - name: Run db update
      run: |-
        pip install -e .
        python3 src/data_extraction/db_handler.py
        git config --global user.name ${{secrets.USER_NAME}}
        git config --global user.email ${{secrets.USER_EMAIL}}
        git add .
        git commit -m "Updating SQLite database"
        git push
        
      
